const express =require("express")
const authRouter = require('../modules/auth/auth.routing')
const serviceRouter =require('../modules/Salonservices/service.routing')
const appintmentRoute=require('../modules/appointment/appointment.routing')
const appointmentRouting = require("../modules/appointment/appointment.routing")
const bulkRouting = require ("../modules/bulk/bulk.routes")
const templateRouting = require("../modules/notification/template.routes")
const logsRouting = require("../modules/logs/logs.routing")
const mainRoute=express.Router()
mainRoute.use('/auth',authRouter)
mainRoute.use('/services',serviceRouter)
mainRoute.use('/appointment',appointmentRouting)
mainRoute.use('/bulk', bulkRouting)
mainRoute.use('/notification',templateRouting)
mainRoute.use('/logs',logsRouting)

module.exports=mainRoute